/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as DesignToolsRouteImport } from './routes/design-tools'
import { Route as DevelopmentToolsRouteImport } from './routes/development-tools'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignToolsRoute = DesignToolsRouteImport.update({
  id: '/design-tools',
  path: '/design-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentToolsRoute = DevelopmentToolsRouteImport.update({
  id: '/development-tools',
  path: '/development-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/deployment': typeof DeploymentRoute
  '/design-tools': typeof DesignToolsRoute
  '/development-tools': typeof DevelopmentToolsRoute
  '/favorites': typeof FavoritesRoute
  '/mobile': typeof MobileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/deployment': typeof DeploymentRoute
  '/design-tools': typeof DesignToolsRoute
  '/development-tools': typeof DevelopmentToolsRoute
  '/favorites': typeof FavoritesRoute
  '/mobile': typeof MobileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/deployment': typeof DeploymentRoute
  '/design-tools': typeof DesignToolsRoute
  '/development-tools': typeof DevelopmentToolsRoute
  '/favorites': typeof FavoritesRoute
  '/mobile': typeof MobileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tools'
    | '/categories'
    | '/dashboard'
    | '/deployment'
    | '/design-tools'
    | '/development-tools'
    | '/favorites'
    | '/mobile'
    | '/resources'
    | '/settings'
    | '/category/$slug'
    | '/tools/$slug'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tools'
    | '/categories'
    | '/dashboard'
    | '/deployment'
    | '/design-tools'
    | '/development-tools'
    | '/favorites'
    | '/mobile'
    | '/resources'
    | '/settings'
    | '/category/$slug'
    | '/tools/$slug'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/ai-tools'
    | '/categories'
    | '/dashboard'
    | '/deployment'
    | '/design-tools'
    | '/development-tools'
    | '/favorites'
    | '/mobile'
    | '/resources'
    | '/settings'
    | '/category/$slug'
    | '/tools/$slug'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToolsRoute: typeof AiToolsRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  DeploymentRoute: typeof DeploymentRoute
  DesignToolsRoute: typeof DesignToolsRoute
  DevelopmentToolsRoute: typeof DevelopmentToolsRoute
  FavoritesRoute: typeof FavoritesRoute
  MobileRoute: typeof MobileRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-tools': {
      id: '/design-tools'
      path: '/design-tools'
      fullPath: '/design-tools'
      preLoaderRoute: typeof DesignToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-tools': {
      id: '/development-tools'
      path: '/development-tools'
      fullPath: '/development-tools'
      preLoaderRoute: typeof DevelopmentToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToolsRoute: AiToolsRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  DeploymentRoute: DeploymentRoute,
  DesignToolsRoute: DesignToolsRoute,
  DevelopmentToolsRoute: DevelopmentToolsRoute,
  FavoritesRoute: FavoritesRoute,
  MobileRoute: MobileRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
